In [2]:
import numpy as np
from numpy import random

In [12]:
c = random.randint(5, size=( 5))

In [15]:
c

array([3, 3, 4, 2, 4])

In [16]:
5/c

array([1.66666667, 1.66666667, 1.25      , 2.5       , 1.25      ])

In [17]:
c/5

array([0.6, 0.6, 0.8, 0.4, 0.8])

In [22]:
# import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
# print 'Our array is:' 
print(x) 
print('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
# print 'The corner elements of this array are:' 
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  2]
 [ 9 10]]
